[project]
name = "rttm"
version = "0.1.0"
description = "RTTM file tool"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.9.2",
    "pympi-ling>=1.70.2",
    "ruff>=0.7.4",
    "pytest>=8.0.0",
]
